name: OYY_APP
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  carousel_slider: ^4.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  json_serializable: ^6.1.0

flutter:
  uses-material-design: true
  assets:
      - lib/assets/images/user.jpg